### PR TITLE
Enable opening when empty by allowing to specify item height

### PR DESCRIPTION
**Pull request by FluffyDiscord**
Workaround for #244

### CODE REVIEW

**Comment by AhmedLSayed9** [comment]
The default behavior for the dropdown button when items are empty is to be disabled.

Therefore, we should instead prevent programmatically opening the dropdown when items are empty.

**Comment by FluffyDiscord** [comment]
As I described in #244 I have a bit unusual use case which this PR makes possible.

I need to show sometimes an empty dropdown with search to the user. The point is that when nothing is found, user can tap on the `noResultsWidget` to create new item and add it to the dropdown using the searched value.

Without this PC the dropdown will not open when empty, due to failing loading item height, because there are no items at all.

**Comment by AhmedLSayed9** [comment]
> As I described in #244 I have a bit unusual use case which this PR makes possible.
> 
> I need to sometimes show an empty dropdown with search. The point is that when nothing is found, user can tap on the `noResultsWidget` to create new item and add it to the dropdown using the searched value.
> 
> Without this PC the dropdown will not open when empty, due to failing loading item height, because there are no items at all, and also due to the `_enabled` check.
> 
> Adding one more property `enableWhenEmpty` would probably make more sense and be backwards compatible too.

If we're going to allow showing an empty dropdown, it should occur whether it's opened programmatically or not.

The thing is, this is a fundamental change that might complicate things for a rare use case, which can be handled in other ways.

Currently, the dropdown behavior is working with already loaded data and the search is happening locally.

The proposed change might be feasible if we support loading/updating items when the dropdown menu is open (https://github.com/AhmedLSayed9/dropdown_button2/issues/111).

For now, If you need to show something when the items are empty, you can just pass a placeholder item that act as `noResultsWidget`. It'll give you the same result :)

**Comment by AhmedLSayed9** [comment]
Opening menu programmatically has been updated.
If items are empty, menu can't be opened manually as it's considered disabled.

**Comment by AhmedLSayed9** [comment]
I'll close this as I don't intend to apply it before we support loading/updating items when the dropdown menu is open.
Thanks anyway!

**Pull request closed without merging**
