### PR TITLE
Add `backgroundColor` to customize dropdown style

### PR DESCRIPTION
**Pull request by bambinoua**
It is good to have possibility to change the dropdown background color especially if standard `DropdownButton` allows this.

### CODE REVIEW

**Comment by AhmedLSayed9** [comment]
Hello!
There's already `DropdownStyleData.backgroundColor` :)

**Comment by bambinoua** [comment]
Hello!

> There's already `DropdownStyleData.backgroundColor` :)

Since when? Yesterday I didn't see it.

**Comment by bambinoua** [comment]
This is line from your code:
https://github.com/AhmedLSayed9/dropdown_button2/blob/bcb169ebfcfcf178c6c30bfb5b7a15f8aa440cce/lib/src/dropdown_button2.dart#L393

This is line from flutter repository:
https://github.com/flutter/flutter/blob/ea1bf240a5f236b3e2560c29e141e3461869ee12/packages/flutter/lib/src/material/dropdown.dart#L273

**Comment by AhmedLSayed9** [comment]
Sorry, I meant `DropdownStyleData.decoration.color`:
https://github.com/AhmedLSayed9/dropdown_button2/blob/bcb169ebfcfcf178c6c30bfb5b7a15f8aa440cce/lib/src/dropdown_button2_data.dart#L139

It's been used at:
https://github.com/AhmedLSayed9/dropdown_button2/blob/bcb169ebfcfcf178c6c30bfb5b7a15f8aa440cce/lib/src/dropdown_button2.dart#L54

**Pull request closed without merging**
