### PR TITLE
Add support for noResultsWidget in DropdownSearchData

### PR DESCRIPTION
**Pull request by chayanforyou**
The widget to display when no suggestions are available.

```dart
DropdownSearchData(
  // ....
  noResultsWidget: const Padding(
    padding: EdgeInsets.all(8),
    child: Text('No Items Found!'),
  )
)
```

### CODE REVIEW

**Comment by chayanforyou** [comment]
@AhmedLSayed9 now take a look please.

**Comment by chayanforyou** [comment]
@AhmedLSayed9 do you have any plan to merge this PR?

**Comment by AhmedLSayed9** [comment]
> @AhmedLSayed9 do you have any plan to merge this PR?

Yes, sure. sorry for the delay response.

I'll merge it today or tomorrow.

**Comment by AhmedLSayed9** [comment]
Thanks!

**Pull request merged**
