### PR TITLE
Add support for searchNotFoundWidget in DropdownSearchData

### PR DESCRIPTION
**Pull request by chayanforyou**
The widget to display when no suggestions are available.

```dart
DropdownSearchData(
  // ....
  searchNotFoundWidget: const Padding(
    padding: EdgeInsets.all(8),
    child: Text('No Items Found!'),
  )
)
```

### CODE REVIEW

**Comment by chayanforyou** [comment]
@AhmedLSayed9 can you take a look please?

**Comment by AhmedLSayed9** [comment]
Can you update ReadMe options to include this too?

**Comment by chayanforyou** [comment]
> @AhmedLSayed9 can you take a look please?

Sure, I have updated the ReadMe and added an example image in this PR

**Comment by chayanforyou** [comment]
@AhmedLSayed9 can you take a look now?

**Comment by AhmedLSayed9** [comment]
@chayanforyou You've missed a pending review above.

**Comment by chayanforyou** [comment]
@AhmedLSayed9 how can it solve the pending review?

**Review by ashikjs — APPROVED** [review]

**Review by ashikjs — CHANGES_REQUESTED** [review]
DId you update readme  for this change

**Review by ashikjs — APPROVED** [review]

**Comment by AhmedLSayed9** [comment]
Here's my review above:

> I think noResultsWidget is a better naming and it should come after the searchInnerWidgetHeight property.
> Also, I think we should rename searchInnerWidget[Height] to searchBarWidget[Height] (it should be in another PR)

**Comment by chayanforyou** [comment]
> Ignore the `searchInnerWidget`, I'll take care of that.

Thanks. Please add it to next release.

**Comment by AhmedLSayed9** [comment]
Why did you close the PR? 😆

**Comment by AhmedLSayed9** [comment]
I was just asking to rename `searchNotFoundWidget` to `noResultsWidget` and put it after `searchInnerWidgetHeight`.
You can open a new PR with these edits. Thanks!

**Pull request closed without merging**
